.TH "jsonltocsv" "1" "September 8, 2015" "" ""
.SH NAME
.PP
jsonltocsv \- sample lines randomly from input
.SH SYNOPSIS
.PP
\f[B]jsonltocsv\f[] [\f[I]file\f[]]
.SH DESCRIPTION
.PP
Jsonltocsv is a program that converts a stream of json lines into a
csv\-formatted stream
.SH OPTIONS
.TP
.B \f[I]file\f[]
a file to read, if file is absent, input is stdin
.RS
.RE
.SH AUTHORS
Chris Wheeler (cmwhee\@gmail.com).
